# Configuración de la aplicación
server.port=8081

# Configuración de base de datos (deshabilitada por defecto)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Configuración de logging
logging.level.Jasper=INFO
logging.level.org.springframework=WARN

# Configuración de JasperReports
jasper.reports.path=classpath:reports/
